server:
  port: 8082
spring:
  application:
    name: customer-service
  datasource:
    password: vullnet2004
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true


